[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
ROOT_DIR = "{{config_root}}"

[tasks.deps]
description = "Install Python dependencies"
run = "uv pip install -r requirements.txt"

[tools]
"python" = "3.13"
"uv" = "latest"
